version: '3'
services:
  api:
    environment: # for a full list check the corresponding properties-builder file
    - DB_DATABASE=dashboarddb
    - DB_HOST=db
    - DB_PORT=27017
    - DB_USERNAME=dashboarduser
    - DB_PASSWORD=dbpassword
    volumes:
    - ./logs:/hygieia/logs
  github-collector:
    environment:
    - GITHUB_HOST=https://github.com/daniel-cespedesm/gl-devops_challenge
    - GITHUB_CRON=0 * * * * *
    - GITHUB_COMMIT_THRESHOLD_DAYS=300
  jenkins-build-collector:
    environment:
    - JENKINS_CRON=0 * * * * *
    - JENKINS_MASTER=http://10.0.0.7:8081
    - JENKINS_USERNAME=gorilla
    - JENKINS_PASSWORD=GorillaLogic
  jenkins-cucumber-test-collector:
    environment:
    - JENKINS_CRON=0 * * * * *
    - JENKINS_MASTER=http://10.0.0.7:8081
    - JENKINS_USERNAME=gorilla
    - JENKINS_PASSWORD=GorillaLogic
    - JENKINS_CUCUMBER_JSON_FILENAME=cucumber-report.json
